### ISSUE TITLE
Can we get this to run automatically?

### ISSUE THREAD

**Issue by reuven** [mattijn/pycodestyle_magic#10]
I'm curious — is there a chance that we can get pycodestyle_magic to run automatically on each cell?  Or must I invoke it manually?

Thanks for this great plugin!

**Comment by mattijn** [comment]
I like the idea, but I don't know what effort is required. Feel free to investigate;)

**Comment by psychemedia** [comment]
The [`nb_black`](https://github.com/dnanhkhoa/nb_black) magic runs automatically whenever a code cell is run.

The trick behind this appears to be through the invocation of a `post_run_cell` IPython event: https://github.com/dnanhkhoa/nb_black/blob/faf69f68a39a106aaa4c6fd7ee5226ade9c85abc/nb_black.py#L11

**Comment by mattijn** [comment]
I've made a new release including some new magic functions:
- `%flake8_on`: turn ON the auto-flake8-checking (function should be called only once)
- `%flake8_off`: turn OFF the auto-flake8-checking 
- `%pycodestyle_on`: turn ON the auto-pycodestyle-checking (function should be called only once)
- `%pycodestyle_off`: turn OFF the auto-pycodestyle-checking 

I've tested it on macOS and it seems to work fine. Please let me know if it doesn't work for you.

**Comment by reuven** [comment]
Just tried it, also on a Mac.  **This is fantastic.  Thank you.**
