### ISSUE TITLE
Disabling application of flake8 in a specific cell

### ISSUE THREAD

**Issue by psychemedia** [mattijn/pycodestyle_magic#13]
When running code cells that contain IPython directives to execute commands on the command line (eg `! echo 'Hello world"`) or cell block magics (eg `%%capture`), the code linter will report an error.

Whilst it is possible to include a `%flake8_on` magic in the preceding code cell and a restorative `%flake8_on` command at the end of such a cell to disable warnings associated with such cells, it would be useful if there was a way of disabling the execution of the *flake8* linter in a couple of ways:

- if a code cell starts with `%%`;
- if a code cell starts with a `%flake8_disable` or `%flake8_quiet` magic.

**Comment by mattijn** [comment]
Fixed by https://github.com/mattijn/pycodestyle_magic/issues/13

> It should now be possible to use all magic functions (starting with `!`, `&&` or `%`) without being checked by `flake8` or `pycodestyle`

**Comment by mattijn** [comment]
I also released version 0.4 on pip with this functionality included
