### ISSUE TITLE
%pycodestyle_on and %flake8_on produce errors

### ISSUE THREAD

**Issue by cmichal2** [mattijn/pycodestyle_magic#18]
I've recently installed pycodestyle-0.5 on a number of linux systems (Ubuntu and Gentoo), installed with pip and on all of them cannot use the auto-checking commands: %pycodestyle_on and %flake8_on.

%pycodestyle_on gives the error:

> Error in callback <bound method VarWatcher.auto_run_pycodestyle of <pycodestyle_magic.VarWatcher object at 0x7f742c0687f0>> (for post_run_cell):
> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> TypeError: auto_run_pycodestyle() missing 1 required positional argument: 'result'
> 
> 
> 

as soon as it is invoked, and then in any cell that is executed. %flake8_on produces a similar error.

I have pycodestyle-2.3.1 and python-3.6.

**Comment by mattijn** [comment]
Hmm, I cannot reproduce this one.
What is your IPython version?

The `flake8_on` and `pycodestyle_on` magic functions use the `post_run_cell` event callbacks that were added in IPython 6.3.

If I do the following in a notebook cell:
```
!ipython --version
```
I get:  `7.5.0`

**Comment by cmichal2** [comment]
Ah sorry - that does appear to be my problem. All of these systems appear to have ipython 5.x.

Thanks!

**Comment by mattijn** [comment]
No problem, glad you solved it!
